driver:
  name: vagrant
  require_chef_omnibus: 13

platforms:
- name: ubuntu-16.04
- name: ubuntu-14.04
- name: debian-9
- name: debian-8

suites:
- name: default
  run_list:
  - recipe[apt]
  - recipe[supervisor]
